[build]
    publish = "_dist"

[context.production]
    [context.production.environment]
        YARN_VERSION = "0.18.1"

[context.deploy-preview.environment]
    YARN_VERSION = "0.18.1"

[context.branch-deploy.environment]
    YARN_VERSION = "0.18.1"
